<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="CL-NB-918" failures="1" tests="2" name="Test login incorrecto" time="15.538" errors="0" timestamp="2021-11-17T20:17:46 CLST">
  <testcase classname="frameWorkAutomatizacionA_Castro.automatizacion.LoginIncorrecto" name="BaseNavegacionPag" time="7.57"/>
  <testcase classname="frameWorkAutomatizacionA_Castro.automatizacion.LoginIncorrecto" name="obtenerValidacion" time="0.012">
    <failure type="java.lang.AssertionError" message="expected [Tableros | Trello] but found [Inicia sesi贸n para continuar - Iniciar sesi贸n con la cuenta de Atlassian]">
      <![CDATA[java.lang.AssertionError: expected [Tableros | Trello] but found [Inicia sesi贸n para continuar - Iniciar sesi贸n con la cuenta de Atlassian]
at frameWorkAutomatizacionA_Castro.automatizacion.LoginIncorrecto.obtenerValidacion(LoginIncorrecto.java:76)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- obtenerValidacion -->
</testsuite> <!-- Test login incorrecto -->
